before_install:
- sudo chmod 755 ./vendor/bin/youtube-dl
- sudo apt-get update -qq
#- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#- chmod +x ./cc-test-reporter
#- ./cc-test-reporter before-build

#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

bundler_args: --without extras

rvm:
- 2.3.8
- 2.4.5
- 2.5.5
- 2.6.2
- ruby-head # MRI head
- jruby # JRuby RVM default
- jruby-9.1.2.0 # JRuby 9k series
- jruby-head # JRuby Head
- rbx-2 # Rubinius stable

cache: bundler

matrix:
  allow_failures:
  - rvm: jruby
  - rvm: jruby-head
  - rvm: ruby-head
  - rvm: rbx-2

notifications:
  slack: layer8x:cvixULdjCINfq7u9Zs1rS0VY
  email: false
